"""add key findings and recommendations to insights

Revision ID: 0894032ddf54
Revises: 6c112c42da57
Create Date: 2026-05-31 00:50:48.804842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0894032ddf54'
down_revision: Union[str, None] = '6c112c42da57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('insights', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'recommendations')
    op.drop_column('insights', 'key_findings')
    # ### end Alembic commands ###
