"""add key findings recommendations

Revision ID: 8eee1f0fd62d
Revises: 1418c0fb0d19
Create Date: 2026-05-31 17:21:01.964886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eee1f0fd62d'
down_revision: Union[str, None] = '1418c0fb0d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
