"""add key findings recommendations

Revision ID: ceb1ea442ace
Revises: ffc47c1c68f5
Create Date: 2026-05-31 01:24:37.617229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb1ea442ace'
down_revision: Union[str, None] = 'ffc47c1c68f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
