"""add key findings recommendations to insight

Revision ID: ffc47c1c68f5
Revises: cd4759d5f13d
Create Date: 2026-05-31 01:18:21.940321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc47c1c68f5'
down_revision: Union[str, None] = 'cd4759d5f13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
